-- ============================================================
-- InMind · flow_sessions — parent record for every check-in
-- ============================================================

create table public.flow_sessions (
  id                int4 generated by default as identity primary key,
  session_id        varchar not null,
  user_id           uuid not null references public.users(id) on delete cascade,
  flow_type         varchar not null,
  started_at        timestamptz not null,
  completed_at      timestamptz,
  total_duration_ms int4,
  total_steps       int4,
  steps_completed   int4,
  engagement_score  int4,
  engagement_label  varchar,
  is_genuine        boolean default true,
  flags             text[] default '{}'::text[],
  created_at        timestamptz default now(),

  constraint flow_sessions_session_id_key unique (session_id),
  constraint flow_sessions_flow_type_check check (flow_type in ('static', 'dynamic')),
  constraint flow_sessions_engagement_score_check
    check (engagement_score >= 0 and engagement_score <= 100)
);

-- Indexes
create index idx_flow_sessions_user on public.flow_sessions (user_id);
create index idx_flow_sessions_type on public.flow_sessions (flow_type);
create index idx_flow_sessions_date on public.flow_sessions (started_at);
create index idx_flow_sessions_genuine on public.flow_sessions (is_genuine)
  where is_genuine = false;

-- RLS
alter table public.flow_sessions enable row level security;

create policy flow_sessions_own on public.flow_sessions
  for all using (
    user_id = auth.uid()
    or "current_role"() = any (array['admin'::user_role, 'teacher'::user_role])
  )
  with check (user_id = auth.uid());
